### PR TITLE
Add ?title=

### PR DESCRIPTION
**Pull request by Bax3n**
?title=TITLE will now open the extension with that title

### CODE REVIEW

**Comment by savaka2** [comment]
The id used for extBox() is inconsistent, if a new extension is added to the list these numbers will change (because the list is alphabetical and it's the index in the list). This is a good idea but it will have to be done differently

**Comment by savaka2** [comment]
For `extBox(ind)` ind is the index in sortExts, so it needs to convert index in extensions to index in sortExts

**Comment by savaka2** [comment]
So is it qso.title now because you put the actual title of the extension in the query string?

**Comment by Bax3n** [comment]
Yeah, `qso.title` would get the title of the extension that it searches for.

The variable `searchTitle` has the value of `qso.title.split('+').join(' ')`

**Comment by savaka2** [comment]
I'm just going to use `.replace(/\+/g, ' ')` (should replace all +s with spaces)

**Comment by savaka2** [comment]
ok this should work and I need to test it so I'm going to merge it

**Pull request merged**
