### PR TITLE
Filters in URL

### PR DESCRIPTION
**Pull request by Bax3n**
### Now you can put certain filters in the URL to filter your search.

will search for any extensions made by savaka

> ?type=w

will search for any web extensions

> ?type=w?author=savaka

will search for any web extensions made by savaka

#### Images: 

demo

### CODE REVIEW

**Comment by Bax3n** [comment]
There was a problem with queryString where
> queryStringObj("?author=savaka?type=w")

returns 

> {author: "savaka?type"}

instead of 

> {author: "savaka",type: "w"}


This limits it to only one tag.

**Comment by savaka2** [comment]
Querystrings are formatted `?a=x&b=y&c=d`

**Comment by Bax3n** [comment]
OK

**Comment by savaka2** [comment]
You can now also do `?sample` or `?listed`
40e7452

**Pull request merged**
